#!/bin/sh

uci set system.@system[0].hostname='ZN-M2'

uci set firewall.@defaults[0].flow_offloading='1'
uci set firewall.@defaults[0].flow_offloading_hw='1'

uci set network.lan.ipv6='1'

uci commit system
uci commit firewall
uci commit network

/etc/init.d/firewall restart

exit 0
